TEAM_CODES = {
  "GSW": "Golden State Warriors",
  "DET": "Detroit Pistons",
  "WSB": "Washington Bullets",
  "LAC": "Los Angeles Clippers",
  "DAL": "Dallas Mavericks",
  "BOS": "Boston Celtics",
  "MEM": "Memphis Grizzlies",
  "UTA": "Utah Jazz",
  "MIN": "Minnesota Timberwolves",
  "NJN": "New Jersey Nets",
  "TOR": "Toronto Raptors",
  "BKN": "Brooklyn Nets",
  "DEN": "Denver Nuggets",
  "WAS": "Washington Wizards",
  "PHI": "Philadelphia 76ers",
  "POR": "Portland Trailblazers",
  "IND": "Indiana Pacers",
  "MIL": "Milwaukee Bucks",
  "SAC": "Sacramento Kings",
  "ATL": "Atlanta Hawks",
  "ORL": "Orlando Magic",
  "VAN": "Vancouver Grizzlies",
  "OKC": "Oklahoma City Thunder",
  "LAL": "Los Angeles Lakers",
  "SDC": "San Diego Clippers",
  "NOH": "New Orleans Hornets",
  "NYK": "New York Knicks",
  "CHH": "Charlotte Hornets", # same as CHO
  "SEA": "Seattle Supersonics",
  "NOP": "New Orleans Pelicans",
  "NOK": "",
  "PHX": "Phoenix Suns",
  "CHA": "Charlotte Hornets",
  "MIA": "Miami Heat",
  "CLE": "Cleveland Cavaliers",
  "CHO": "Charlotte Hornets", # same as CHH
  "CHB": "Charlotte Bobcats",
  "CHI": "Chicago Bulls",
  "SAS": "San Antonio Spurs",
  "KCK": "Kansas City Kings",
  "HOU": "Houston Rockets",
}
