scrape_gamelogs: python3 scrape_gamelogs.py
scrape_players: python3 scrape_nba_players.py
scrape_nba_game_recaps: python3 scrape_nba_game_recaps.py
scrape_espn_game_recaps: python3 scrape_espn_game_recaps.py
run_switching_experiment: python3 run_switching_experiment.py
